#=================================================================================
# 容器相关设置
#=================================================================================
# spring 组件相关设置
#=================================================================================
# 其他辅助框架相关配置
#=================================================================================
# 自定义参数相关配置
config-service:
    name: "github-2"
#=================================================================================
